# Generated by Django 4.2 on 2023-04-22 08:13

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/img/user_pic.jpeg', null=True, upload_to=users_app.models.upload_to, verbose_name='profile_pic'),
        ),
    ]
